# -*- coding: utf-8 -*-
"""CSC3005-2 (GROUP ASSIGNMENT)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6cSdZ5KaX2NCHM-rYw9XrPYak2LziUd
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

import warnings
warnings.filterwarnings("ignore")

# Data Collection
import pandas as pd

# Load dataset
df = pd.read_csv("/content/food_order.csv")

# Display first 5 rows
df.head()

# Data Understanding
# Check Dataset Information
df.info()

# Statistical Summary
df.describe()

# Check Shape
print(df.shape)

# Check Data Type
print(df.dtypes)

# Data Cleaning
# Check Missing Value
df.isnull().sum()

# Remove Duplicates
df.drop_duplicates(inplace=True)

# Check Duplicates Rows
print(df.duplicated().sum())

# Fill Missing Ratings
df['rating'].fillna(df['rating'].mode()[0], inplace=True)

# Import Visualization Libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Order Cost Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['cost_of_the_order'], bins=30, color='orange')
plt.title("Distribution of Order Cost")
plt.show()

# Delivery Time Distribution
plt.figure(figsize=(8,5))
sns.histplot(df['delivery_time'], bins=20, color='pink')
plt.title("Distribution of Delivery Time")
plt.show()

# Cuisine Type
plt.figure(figsize=(10,6))
sns.countplot(y='cuisine_type', data=df,
              order=df['cuisine_type'].value_counts().index, color='brown')
plt.title("Cuisine Types")
plt.show()

# Ratings Distribution
sns.countplot(x='rating', data=df, color='purple')
plt.title("Customer Ratings")
plt.show()

# Correlation Heatmap
numeric_df = df.select_dtypes(include=['int64','float64'])

plt.figure(figsize=(8,6))
sns.heatmap(numeric_df.corr(),
            annot=True,
            cmap='coolwarm')
plt.show()

# Data Preprocessing
# Find the median delivery time
median_time = df['delivery_time'].median()

print("Median Delivery Time:", median_time)

# Create target variable
df['delivery_status'] = df['delivery_time'].apply(
    lambda x: 'Fast' if x <= median_time else 'Late'
)

# Check class distribution
print(df['delivery_status'].value_counts())

# Features Variables
X = df[[
    'restaurant_name',
    'cuisine_type',
    'cost_of_the_order',
    'day_of_the_week',
    'food_preparation_time'
]]

y = df['delivery_status']

# Train-test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Feature Scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Input variables
X = df[[
    'restaurant_name',
    'cuisine_type',
    'cost_of_the_order',
    'day_of_the_week',
    'food_preparation_time'
]]

# Convert categorical variables
X = pd.get_dummies(
    X,
    columns=['restaurant_name', 'cuisine_type', 'day_of_the_week'],
    drop_first=True
)

# Output variable
y = df['delivery_status']

# Machine Learning Models
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

prediction_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, prediction_dt)

print("Decision Tree Accuracy:", accuracy_dt)

# Decision Tree Visualization
# The real one
from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))

tree.plot_tree(
    dt,
    filled=True,
    feature_names=X.columns,
    class_names=[str(i) for i in sorted(y.unique())],
    rounded=True,
    fontsize=8
)

plt.title("Decision Tree Visualization")
plt.show()

# Decision Tree Confusion Matrix
# Shows how correct or incorrect your model predictions are in detail not only by proving the accuracy value

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm_dt = confusion_matrix(y_test, prediction_dt)

plt.figure(figsize=(6,5))
sns.heatmap(cm_dt,
            annot=True,
            cmap='Blues',
            fmt='d')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Decision Tree Confusion Matrix")
plt.show()

# Machine Learning Models
# Random Forest
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

prediction_rf = rf.predict(X_test)

accuracy_rf = accuracy_score(y_test, prediction_rf)

print("Random Forest Accuracy:", accuracy_rf)

print(classification_report(y_test, prediction_dt))

# Visualization of Random Forest
# Using Feature Importance Bar Chart

status_counts = pd.crosstab(df['cost_of_the_order'], df['delivery_status'])

status_counts.plot(kind='bar', figsize=(10,6))

plt.title('Delivery Status by Restaurant')
plt.xlabel('cost_of_the_order')
plt.ylabel('delivery_status')
plt.xticks(rotation=45)
plt.legend(title='Status')
plt.tight_layout()
plt.show()

# Random Forest Confusion Matrix
cm_rf = confusion_matrix(y_test, prediction_rf)

plt.figure(figsize=(6,5))

sns.heatmap(cm_rf,
            annot=True,
            cmap='Greens',
            fmt='d')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")

plt.show()

# Machine Learning Models
# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

prediction_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, prediction_knn)

print("KNN Accuracy:", accuracy_knn)

# Model evaluation
# Clasification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, prediction_dt))

# KNN Visualization
# Scatter plot
plt.figure(figsize=(8,6))

plt.scatter(
    df['cost_of_the_order'],
    df['delivery_status'],
    alpha=0.6
)

plt.xlabel('Cost (RM)')
plt.ylabel('Delivery status (minutes)')
plt.title('Cost vs Delivery Time')
plt.grid(True)

plt.show()

# KNN Confusion Matrix

cm_knn = confusion_matrix(y_test, prediction_knn)

plt.figure(figsize=(6,5))

sns.heatmap(cm_knn,
            annot=True,
            cmap='Oranges',
            fmt='d')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("KNN Confusion Matrix")

plt.show()

# Model Evaluation
# Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test,prediction_dt))

# Compare Models accuracy value

comparison = pd.DataFrame({

'Model':['Decision Tree',
         'Random Forest',
         'KNN'],

'Accuracy':[accuracy_dt,
            accuracy_rf,
            accuracy_knn]

})

comparison

# Model Comparison of the three Machine Learning Algorithm accuracy value
sns.barplot(data=comparison,
            x='Model',
            y='Accuracy',
            color='green')

plt.title("Model Comparison")
plt.show()