# -*- coding: utf-8 -*-
"""FOOD ORDER ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBTDWcGbKIUunN_CqoEkX-fgxPyNqT2y
"""

# Data manipulation
import pandas as pd
import numpy as np

# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Data preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Machine Learning Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Evaluation
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

df = pd.read_csv("/content/food_order.csv")

# Display first 5 rows
df.head()

df.info()

print("Rows and Columns:", df.shape)

df.describe()

df.dtypes

df.isnull().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df['rating'].fillna(df['rating'].mode()[0], inplace=True)

df.info()

plt.figure(figsize=(8,5))
sns.histplot(df['cost_of_the_order'], bins=30)
plt.title("Distribution of Order Cost")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['delivery_time'], bins=20)
plt.title("Distribution of Delivery Time")
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(
    y='cuisine_type',
    data=df,
    order=df['cuisine_type'].value_counts().index
)

plt.title("Cuisine Type Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(x='rating', data=df)

plt.title("Customer Ratings")
plt.show()

plt.figure(figsize=(8,6))

numeric = df.select_dtypes(include=['int64','float64'])

sns.heatmap(
    numeric.corr(),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

median_time = df['delivery_time'].median()

print("Median Delivery Time:", median_time)

df['delivery_status'] = df['delivery_time'].apply(
    lambda x: 'Fast' if x <= median_time else 'Late'
)

df[['delivery_time','delivery_status']].head()

X = df[
    [
        'restaurant_name',
        'cuisine_type',
        'cost_of_the_order',
        'day_of_the_week',
        'food_preparation_time'
    ]
]

y = df['delivery_status']

X = pd.get_dummies(
    X,
    columns=[
        'restaurant_name',
        'cuisine_type',
        'day_of_the_week'
    ],
    drop_first=True
)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

prediction_dt = dt.predict(X_test)

accuracy_dt = accuracy_score(y_test, prediction_dt)

print("Decision Tree Accuracy:", accuracy_dt)

from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))

tree.plot_tree(
    dt,
    feature_names=X.columns,
    class_names=dt.classes_,
    filled=True,
    rounded=True,
    fontsize=8
)

plt.title("Decision Tree Visualization")

plt.show()

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

prediction_rf = rf.predict(X_test)

accuracy_rf = accuracy_score(y_test, prediction_rf)

print("Random Forest Accuracy:", accuracy_rf)

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

prediction_knn = knn.predict(X_test)

accuracy_knn = accuracy_score(y_test, prediction_knn)

print("KNN Accuracy:", accuracy_knn)

print(classification_report(y_test, prediction_dt))

cm_dt = confusion_matrix(y_test, prediction_dt)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_dt,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("Decision Tree Confusion Matrix")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.show()

print(classification_report(y_test, prediction_rf))

cm_rf = confusion_matrix(y_test, prediction_rf)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_rf,
    annot=True,
    fmt='d',
    cmap='Greens'
)

plt.title("Random Forest Confusion Matrix")

plt.show()

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

plt.figure(figsize=(10,8))

plt.barh(
    importance['Feature'],
    importance['Importance']
)

plt.gca().invert_yaxis()

plt.title("Feature Importance")

plt.show()

print(classification_report(y_test, prediction_knn))

cm_knn = confusion_matrix(y_test, prediction_knn)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm_knn,
    annot=True,
    fmt='d',
    cmap='Oranges'
)

plt.title("KNN Confusion Matrix")

plt.show()

print(classification_report(y_test, prediction_rf))

accuracy = []

for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(X_train,y_train)

    pred = model.predict(X_test)

    accuracy.append(
        accuracy_score(y_test,pred)
    )

plt.figure(figsize=(8,5))

plt.plot(range(1,21),accuracy,marker='o')

plt.xlabel("K Value")

plt.ylabel("Accuracy")

plt.title("Accuracy vs K Value")

plt.grid(True)

plt.show()

accuracy = []

for k in range(1,21):

    model = KNeighborsClassifier(n_neighbors=k)

    model.fit(X_train,y_train)

    pred = model.predict(X_test)

    accuracy.append(
        accuracy_score(y_test,pred)
    )

plt.figure(figsize=(8,5))

plt.plot(range(1,21),accuracy,marker='o')

plt.xlabel("K Value")

plt.ylabel("Accuracy")

plt.title("Accuracy vs K Value")

plt.grid(True)

plt.show()

comparison = pd.DataFrame({
    'Model':[
        'Decision Tree',
        'Random Forest',
        'KNN'
    ],
    'Accuracy':[
        accuracy_dt,
        accuracy_rf,
        accuracy_knn
    ]
})

comparison

plt.figure(figsize=(8,5))

sns.barplot(
    data=comparison,
    x='Model',
    y='Accuracy'
)

plt.title("Machine Learning Model Comparison")

for index, value in enumerate(comparison['Accuracy']):
    plt.text(index, value, round(value,3), ha='center')

plt.show()